backoffice_offices_list:
    path:     /backoffice/offices/list
    defaults: { _controller: AppOfficeBundle:Office:list }
frontpage_office_show:
    path:     /biurawgn/{id},{name}.html
    defaults: { _controller: AppOfficeBundle:Office:show }
frontpage_office_agent_show:
    path:     /biurawgn/agent
    defaults: { _controller: AppOfficeBundle:Office:getAgent }
frontpage_office_send_message:
    path:     /biurawgn/wsylij/wiadomosc
    defaults: { _controller: AppOfficeBundle:Office:sendMessage }
frontpage_office_search:
    path:     /biurawgn/szukaj.html
    defaults: { _controller: AppOfficeBundle:Office:search}
backoffice_office_add:
    path:     /backoffice/office/add
    defaults: { _controller: AppOfficeBundle:Office:add }
backoffice_office_edit:
    path:     /backoffice/myoffice/edit
    defaults: { _controller: AppOfficeBundle:Office:edit }
backoffice_office_change_publish:
    path:     /backoffice/office/changePublish
    defaults: { _controller: AppOfficeBundle:Office:changePublish }
backoffice_office_image_add:
    path:     /backoffice/myoffice/{id}/image/add
    defaults: { _controller: AppOfficeBundle:Image:add}

backoffice_office_image_delete:
    path:     /backoffice/myoffice/image/delete
    defaults: { _controller: AppOfficeBundle:Image:delete}

backoffice_agent_list:
    pattern:   /backoffice/office/agents/list
    defaults:  { _controller: AppOfficeBundle:Office:agentsList }
backoffice_sortable_agent_list:
    pattern:   /backoffice/office/agents/sortableList
    defaults:  { _controller: AppOfficeBundle:Office:sortableAgentsList }
backoffice_office_agent_add:
    pattern:   /backoffice/office/user/add
    defaults:  { _controller: AppUserBundle:User:add }
backoffice_office_agent_edit:
    pattern:   /backoffice/office/user/edit
    defaults:  { _controller: AppUserBundle:User:edit }
backoffice_office_agent_change_password:
    pattern:   /backoffice/office/user/changePassword
    defaults:  { _controller: AppUserBundle:BackOfficeSecurity:changePassword }
backoffice_office_agent_enabled:
    pattern:   /backoffice/office/user/enabled
    defaults:  { _controller: AppUserBundle:User:enabled}
backoffice_office_agent_enable_office_management:
    pattern:   /backoffice/office/user/enableOfficeManagement
    defaults:  { _controller: AppUserBundle:User:enableOfficeManagement}
backoffice_office_agent_delete:
    pattern:   /backoffice/office/user/delete
    defaults:  { _controller: AppUserBundle:User:delete}
backoffice_office_images_sort:
    path:     /backoffice/myoffice/images/sort
    defaults: { _controller: AppOfficeBundle:Image:sort}
backoffice_my_office:
    path:     /backoffice/myoffice
    defaults: { _controller: AppOfficeBundle:Office:showMy}

backoffice_office_link_list:
    pattern:   /backoffice/office/{idOffice}/links/list
    defaults:  { _controller: AppOfficeBundle:Link:list }

backoffice_office_link_add:
    pattern:   /backoffice/office/{idOffice}/link/add
    defaults:  { _controller: AppOfficeBundle:Link:add }

backoffice_office_link_delete:
    pattern:   /backoffice/office/link/{id}/delete
    defaults:  { _controller: AppOfficeBundle:Link:delete }

backoffice_office_link_edit:
    pattern:   /backoffice/office/link/{id}/edit
    defaults:  { _controller: AppOfficeBundle:Link:edit }

backoffice_office_link_change_order:
    pattern:   /backoffice/office/link/{id}/order/{direction}
    defaults: { _controller: AppOfficeBundle:Link:changeOrdering }
