App\OfficeBundle\Entity\Office:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: subdomain, message: "Subdomena jest już zajęta." , groups:[registration]}

App\OfficeBundle\Entity\Link:
    properties:
        name:
            - NotBlank: ~
        url:
          - NotBlank: ~
        color:
          - NotBlank: ~
