<?php
/**
 * This file is part of the AppOfferBundle package.
 *
 */
namespace App\OfferBundle\Entity;

/**
 * Class LocalizationRepository
 *
 * @author wojciech przygoda
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalizationRepository extends \Doctrine\ORM\EntityRepository
{
}
