<?php

namespace App\OfferBundle\Entity;

/**
 * SearchStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchStatisticsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $limit
     * @return array
     */
    public function findBestResults($limit){
//        $qb = $this->createQueryBuilder('s');
//        $qb ->select('s,c,t,l')
//            ->join('s.category','c')
//            ->join('s.transaction','t')
//            ->join(LocationAutocomplete::class, 'l', 'WITH', 's.locationId = l.id')
//            ->orderBy('s.displayCounter','desc')
//            ->setMaxResults($limit);
//
//        return $qb->getQuery()->getArrayResult();
        $conn = $this->getEntityManager()->getConnection();
        $sql = "Select s.id, c.name AS category_name, c.id AS category_id, t.name AS trasaction_name, t.id AS transaction_id, l.uniqueKey, l.city AS location_city, l.name AS location_name FROM search_statistics s "
               ." JOIN category c ON s.category_id = c.id JOIN transaction_type t ON s.transaction_type_id = t.id "
                ." JOIN location_autocomplete l ON s.location_id = l.id ORDER BY s.displayCounter DESC LIMIT :limit;";

        $stmt = $conn->prepare($sql);
        $stmt->bindValue('limit',(int)$limit,\PDO::PARAM_INT);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
