services:
    sitemap.twig.filter_extension:
        class: App\SitemapBundle\Twig\FilterExtension
        tags:
            - { name: twig.extension }

    article.sitemap.manager:
        class: App\SitemapBundle\Services\ArticlesSitemapManager
        arguments: [@doctrine.orm.entity_manager,@templating,'%kernel.root_dir%']

    offers.sitemap.manager:
        class: App\SitemapBundle\Services\OffersSitemapManager
        arguments: [@doctrine.orm.entity_manager,@templating,'%kernel.root_dir%']

    sitemap.manager:
        class: App\SitemapBundle\Services\SitemapManager
        arguments: [@doctrine.orm.entity_manager,@templating,'%kernel.root_dir%']

