app_archiv_homepage:
    path:     /
    host:     "archiwum.{domain}"
    defaults:
        _controller: AppArchiveBundle:FrontPage:show
        domain: '%domain%'
    requirements:
        domain: '%domain%'
