services:
    ad.manager:
        class: App\AdBundle\Services\AdManager
        arguments: [@service_container]
    adposition.manager:
        class: App\AdBundle\Services\AdPositionManager
        arguments: [@service_container]
    ad.twig.function_extension:
        class: App\AdBundle\Twig\FunctionExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    block.ad_ads_list:
        class: App\AdBundle\Services\Block\AdsList
        arguments: [@service_container]
    app.ad_voter:
        class: App\AdBundle\Security\AdVoter
        arguments: [@security.access.decision_manager]
        tags:
            - { name: security.voter }
        public: false
    app.ad_position_voter:
        class: App\AdBundle\Security\AdPositionVoter
        arguments: [@security.access.decision_manager]
        tags:
            - { name: security.voter }
        public: false