<?php

namespace App\ArticleBundle\Entity;

/**
 * CategoryOfferDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByParameters($transactionId,$categoryId,$city) {
        $qb = $this->createQueryBuilder('d');
        $qb->join('d.transactionType','t')
           ->join('d.category','c')
           ->where('c.id = :category')
           ->andWhere('t.id = :transaction')
           ->andWhere('d.city = :city')
           ->setParameter('category', $categoryId)
           ->setParameter('transaction', $transactionId)
           ->setParameter('city', $city)
           ->setMaxResults(1)
        ;
        return $qb->getQuery()
            ->useResultCache(true)
            ->setResultCacheLifetime(60*60*24)
            ->getOneOrNullResult();

    }
}
