login:
    pattern:   /login
    defaults:  { _controller: AppUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
backoffice_login:
    pattern:   /backoffice/login
    defaults:  { _controller: AppUserBundle:BackOfficeSecurity:login }

backoffice_login_check:
    pattern:   /backoffice/login_check

backoffice_logout:
    pattern:   /backoffice/logout

backoffice_user_list:
    pattern:   /backoffice/users/list
    defaults:  { _controller: AppUserBundle:User:list }
backoffice_clinet_list:
    pattern:   /backoffice/clients/list
    defaults:  { _controller: AppUserBundle:User:clientsList }
backoffice_client_list:
    pattern:   /backoffice/clients/list
    defaults:  { _controller: AppUserBundle:User:clientsList }

backoffice_officeManager_list:
    pattern:   /backoffice/office/manager/list
    defaults:  { _controller: AppUserBundle:User:officeManagersList }
backoffice_user_add:
    pattern:   /backoffice/user/add
    defaults:  { _controller: AppUserBundle:User:add }
backoffice_user_edit:
    pattern:   /backoffice/user/edit
    defaults:  { _controller: AppUserBundle:User:edit }
backoffice_user_change_password:
    pattern:   /backoffice/user/changePassword
    defaults:  { _controller: AppUserBundle:BackOfficeSecurity:changePassword }
backoffice_user_enabled:
    pattern:   /backoffice/user/enabled
    defaults:  { _controller: AppUserBundle:User:enabled}
backoffice_user_enable_office_management:
    pattern:   /backoffice/user/enableOfficeManagement
    defaults:  { _controller: AppUserBundle:User:enableOfficeManagement}
backoffice_user_delete:
    pattern:   /backoffice/user/delete
    defaults:  { _controller: AppUserBundle:User:delete}
reset_password:
    pattern:   /przypomnienie-hasla.html
    defaults:  { _controller: AppUserBundle:Security:resetPassword}
new_password:
    pattern:   /zmiana-hasla/{securityHash}
    defaults:  { _controller: AppUserBundle:Security:newPassword}
backoffice_reset_password:
    pattern:   /backoffice/przypomnienie-hasla.html
    defaults:  { _controller: AppUserBundle:BackOfficeSecurity:resetPassword}
backoffice_new_password:
    pattern:   /backoffice/zmiana-hasla/{securityHash}
    defaults:  { _controller: AppUserBundle:BackOfficeSecurity:newPassword}
user_account_start:
    pattern:   /moje-konto/
    defaults:  { _controller: AppUserBundle:User:accountStart}
user_account:
    pattern:   /moje-konto/oferty
    defaults:  { _controller: AppUserBundle:User:account}
user_account_observed:
    pattern:   /moje-konto/obserwowane.html
    defaults:  { _controller: AppUserBundle:User:observed}
user_account_payments:
    pattern:   /moje-konto/platnosci.html
    defaults:  { _controller: AppUserBundle:User:payments}
user_account_messages:
    pattern:   /moje-konto/wiadomosci.html
    defaults:  { _controller: AppUserBundle:User:messages}
user_account_message_details:
    pattern:   /moje-konto/wiadomosci/pokaz-szczegoly.html
    defaults:  { _controller: AppUserBundle:User:messageDetails}
user_account_settings:
    pattern:   /moje-konto/ustawienia.html
    defaults:  { _controller: AppUserBundle:User:settings}
user_account_send_message:
    pattern:   /moje-konto/wyslij-wiadomosc.html
    defaults:  { _controller: AppUserBundle:User:sendMessage}
user_account_order_subscription:
    pattern:   /moje-konto/zamow-pakiet.html
    defaults:  { _controller: AppUserBundle:User:order}
user_account_avatar_add:
    pattern:   /moje-konto/dodaj-avatar.html
    defaults:  { _controller: AppUserBundle:Image:add}
user_account_avatar_delete:
    pattern:   /moje-konto/usun-avatar.html
    defaults:  { _controller: AppUserBundle:Image:delete}
registration_buisness_clinet:
    pattern:   /rejestracja-klienci-biznesowi.html
    defaults:  { _controller: AppUserBundle:Security:registrationBuisnessClient}
backoffice_user_change_order:
    pattern:   /backoffice/user/{id}/changeOrdering/{direction}
    defaults:  { _controller: AppUserBundle:User:changeOrdering}