App\UserBundle\Entity\User:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: username, message: "Podany login jest już zarejestrowany." , groups:[registration,users,agents,clients]}
    properties:
        username:
            - NotBlank: {groups: [registration,users,agents,clients], message: "Pole jest wymagane"}
        plainPassword:
            - Length: {min: 8, max: 150 , groups: [registration,users,agents,clients,change_password]}
        file:
            - File:
                maxSize: 10024k
                mimeTypes: [image/jpeg, image/png]
                mimeTypesMessage: Zdjęcie jest niepoprawne
                groups: [users,agents,clients]