app_archive:
    resource: "@AppArchiveBundle/Resources/config/routing.yml"
    prefix:   /

app_article_link:
    resource: "@AppArticleLinkBundle/Resources/config/routing.yml"
    prefix:   /

app_search_link:
    resource: "@AppSearchLinkBundle/Resources/config/routing.yml"
    prefix:   /

app_subscription:
    resource: "@AppSubscriptionBundle/Resources/config/routing.yml"
    prefix:   /

app_newsletter:
    resource: "@AppNewsletterBundle/Resources/config/routing.yml"
    prefix:   /

app_import:
    resource: "@AppImportBundle/Resources/config/routing.yml"
    prefix:   /

app_office:
    resource: "@AppOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app_menu:
    resource: "@AppMenuBundle/Resources/config/routing.yml"
    prefix:   /

app_payment:
    resource: "@AppPaymentBundle/Resources/config/routing.yml"
    prefix:   /

app_offer:
    resource: "@AppOfferBundle/Resources/config/routing.yml"
    prefix:   /

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

app_settings:
    resource: "@AppSettingsBundle/Resources/config/routing.yml"
    prefix:   /

app_ad:
    resource: "@AppAdBundle/Resources/config/routing.yml"
    prefix:   /

app_back_office:
    resource: "@AppBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app_front_page:
    resource: "@AppFrontPageBundle/Resources/config/routing.yml"
    prefix:   /

app_user:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /
app_article:
    resource: "@AppArticleBundle/Resources/config/routing.yml"
    prefix:   /
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
test_email:
    path:     /send-test-email
    defaults: { _controller: AppAppBundle:Default:sendTestEmail }