backoffice_article_link_add:
    path: /backoffice/articleLink/add
    defaults: { _controller: AppArticleLinkBundle:ArticleLink:add }

backoffice_article_link_edit:
    path: /backoffice/articleLink/edit/{id}
    defaults: { _controller: AppArticleLinkBundle:ArticleLink:edit }

backoffice_article_link_delete:
    path: /backoffice/articleLink/delete/{id}
    defaults: { _controller: AppArticleLinkBundle:ArticleLink:delete }

backoffice_article_links_list:
    path: /backoffice/articleLinks/list/
    defaults: { _controller: AppArticleLinkBundle:ArticleLink:list }

backoffice_article_link_change_publish:
    path: /backoffice/articleLink/publish
    defaults: { _controller: AppArticleLinkBundle:ArticleLink:changePublish }

backoffice_article_link_categories_list:
    path: /backoffice/articleLinks/categories/list/
    defaults: { _controller: AppArticleLinkBundle:Category:list }

backoffice_article_link_category_edit:
    path: /backoffice/articleLink/categories/edit/{id}
    defaults: { _controller: AppArticleLinkBundle:Category:edit }

backoffice_article_link_category_add:
    path: /backoffice/articleLink/categories/add
    defaults: { _controller: AppArticleLinkBundle:Category:add }

backoffice_article_link_category_delete:
    path: /backoffice/articleLink/category/delete/{id}
    defaults: { _controller: AppArticleLinkBundle:Category:delete }

backoffice_article_link_change_order:
    path:     /backoffice/articleLink/{id}/order/{direction}
    defaults: { _controller: AppArticleLinkBundle:ArticleLink:changeOrdering}

backoffice_article_link_category_change_order:
    path:     /backoffice/articleLink/category/{id}/order/{direction}
    defaults: { _controller: AppArticleLinkBundle:Category:changeOrdering}