services:
    article_link.manager:
        class: App\ArticleLinkBundle\Services\ArticleLinkManager
        arguments: [@service_container]
    article_link_category.manager:
        class: App\ArticleLinkBundle\Services\LinkCategoryManager
        arguments: [@service_container]
    article_link.twig.function_extension:
        class: App\ArticleLinkBundle\Twig\FunctionExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
