services:
    article.manager:
        class: App\ArticleBundle\Services\ArticleManager
        arguments: [@service_container]
    blog.manager:
        class: App\ArticleBundle\Services\BlogManager
        arguments: [@doctrine.orm.entity_manager, @knp_paginator,@request_stack, @doctrine_cache.providers.main_cache]

    articlecategory.manager:
        class: App\ArticleBundle\Services\ArticleCategoryManager
        arguments: [@service_container]

    block.article_article_list:
        class: App\ArticleBundle\Services\Block\ArticleList
        arguments: [@service_container]
    app.article_voter:
        class: App\ArticleBundle\Security\ArticleVoter
        arguments: [@security.access.decision_manager]
        tags:
            - { name: security.voter }
        public: false

    article_category_description.manager:
        class: App\ArticleBundle\Services\ArticleCategoryDescriptionManager
        arguments: [@doctrine.orm.entity_manager, @knp_paginator,@request_stack, @doctrine_cache.providers.main_cache]

    article.twig.function_extension:
        class: App\ArticleBundle\Twig\FunctionExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    article.twig.filter_extension:
        class: App\ArticleBundle\Twig\FilterExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }