<?php

namespace App\OfferBundle\Repository;

use App\OfferBundle\Entity\Link;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find previous link
     *
     * @param Link $link
     * @return Link
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getPrev($link)
    {
        $qb = $this->createQueryBuilder('l')
            ->where('l.ordering > :ordering')
            ->andWhere('l.offer = :id')
            ->setParameter('ordering', $link->getOrdering())
            ->setParameter('id', $link->getOffer()->getId())
            ->setMaxResults(1)
            ->orderBy('l.ordering','ASC');

        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();

        if(!$result){
            throw new \Exception('Not Found Previous Link');
        }

        return $result;
    }

    /**
     * Find next link
     *
     * @param Link $link
     * @return Link
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getNext($link)
    {
        $qb = $this->createQueryBuilder('l')
            ->where('l.ordering < :ordering')
            ->andWhere('l.offer = :id')
            ->setParameter('ordering', $link->getOrdering())
            ->setParameter('id', $link->getOffer()->getId())
            ->setMaxResults(1)
            ->orderBy('l.ordering','DESC')
        ;

        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();

        if(!$result){
            throw new \Exception('Not Found Next Link');
        }

        return $result;
    }

    /**
     * Get article max ordering
     * @param int $idOffer article link id
     * @return int
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getMaxOrdering($idOffer)
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $sql = "SELECT MAX(ordering) AS maxOrdering FROM offer_link WHERE offer_id = :idOffer";
        $params = array("idOffer" => $idOffer);
        $statement = $connection->prepare($sql);
        $statement->execute($params);

        $maxOrdering = $statement->fetchColumn(0);

        if($maxOrdering){
            return $maxOrdering;
        }

        return 0;
    }

    /**
     * Update Articles ordering
     *
     * @param int $lastOrdering last ordering
     * @param int $idOffer link offer id
     * @throws \Doctrine\DBAL\DBALException
     */
    public function updateOrderingAfterDelete($lastOrdering, $idOffer)
    {
        $sql = "UPDATE offer_link SET ordering = ordering - 1
                         WHERE ordering > :lastOrdering AND offer_id=:offer_id";

        $params = array(
            "offer_id"=> $idOffer,
            "lastOrdering"=> $lastOrdering
        );

        $this->getEntityManager()
            ->getConnection()
            ->prepare($sql)
            ->execute($params);
    }
}
