<?php

namespace App\SettingsBundle\Repository;

/**
 * MyImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRandom()
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT * FROM my_image WHERE isEnabled = 1 ORDER BY RAND() LIMIT 1;';

        $stmt = $conn->prepare($sql);
        $stmt->execute();

        return $stmt->fetch();


    }
}
