backoffice_search_link_add:
    path: /backoffice/searchLink/add
    defaults: { _controller: AppSearchLinkBundle:Link:add }

backoffice_search_link_edit:
    path: /backoffice/searchLink/edit/{id}
    defaults: { _controller: AppSearchLinkBundle:Link:edit }

backoffice_search_link_delete:
    path: /backoffice/searchLink/delete/{id}
    defaults: { _controller: AppSearchLinkBundle:Link:delete }

backoffice_search_links_list:
    path: /backoffice/searchLinks/list/
    defaults: { _controller: AppSearchLinkBundle:Link:list }

backoffice_search_link_change_publish:
    path: /backoffice/searchLink/publish
    defaults: { _controller: AppSearchLinkBundle:Link:changePublish }

backoffice_search_link_categories_list:
    path: /backoffice/searchLinks/categories/list/
    defaults: { _controller: AppSearchLinkBundle:Category:list }

backoffice_search_link_category_edit:
    path: /backoffice/searchLink/categories/edit/{id}
    defaults: { _controller: AppSearchLinkBundle:Category:edit }

backoffice_search_link_change_order:
    path:     /backoffice/searchLink/{id}/order/{direction}
    defaults: { _controller: AppSearchLinkBundle:Link:changeOrdering}

backoffice_search_link_category_change_order:
    path:     /backoffice/searchLink/category/{id}/order/{direction}
    defaults: { _controller: AppSearchLinkBundle:Category:changeOrdering}