services:
    search_link.manager:
        class: App\SearchLinkBundle\Services\LinkManager
        arguments: [@service_container]
    search_link_category.manager:
        class: App\SearchLinkBundle\Services\LinkCategoryManager
        arguments: [@service_container]
    search_link.twig.filter_extension:
        class: App\SearchLinkBundle\Twig\FunctionExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }