<?php

namespace App\AppBundle\Repository;

/**
 * RedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends \Doctrine\ORM\EntityRepository
{
}
