<?php

namespace App\AppBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRatingStats(){
        $query = $this->getEntityManager()
                      ->createQuery("SELECT AVG(v.value) as avg_rate, Count(v) as rate_count
        FROM AppAppBundle:Vote v");

        return $query->useResultCache(true, 60*60*1, 'rating')
                     ->getSingleResult();
    }
}
