services:
    app.twig.function_extension:
        class: App\AppBundle\Twig\FunctionExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    block.manager:
        class: App\AppBundle\Services\BlockManager
        arguments: [@service_container]
    subdomain.manager:
        class: App\AppBundle\Services\SubdomainManager
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            - "@doctrine_cache.providers.main_cache"
            - "%cache_lifetime%"

    rating.manager:
        class: App\AppBundle\Services\RatingManager
        arguments: [@doctrine.orm.entity_manager]

    block.app_custom_link:
        class: App\AppBundle\Services\Block\CustomLink
        arguments: [@service_container]
    block.app_custom_html:
        class: App\AppBundle\Services\Block\CustomHtml
        arguments: [@service_container]

    page_load_listener:
        class: App\AppBundle\EventListener\RedirectListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 64 }