payment_przelewy24_status:
    path:     /payment/przelewy24/status
    defaults: { _controller: AppPaymentBundle:Przelewy24:status }
payment_przelewy24_promo_status:
    path:     /payment/przelewy24/promoStatus
    defaults: { _controller: AppPaymentBundle:Przelewy24:promoStatus }
backoffice_payment_list:
    path:     /backoffice/payment/list
    defaults: { _controller: AppPaymentBundle:Payment:list }
backoffice_invoices_list:
    path:     /backoffice/invoices/list
    defaults: { _controller: AppPaymentBundle:Invoice:list }
backoffice_invoice_details:
    path:     /backoffice/invoice/details
    defaults: { _controller: AppPaymentBundle:Invoice:details }
backoffice_payment_details:
    path:     /backoffice/payment/details
    defaults: { _controller: AppPaymentBundle:Payment:details }
frontpage_payment_details:
    path:     /moje-konto/platnosci/szczegoly.html
    defaults: { _controller: AppPaymentBundle:Payment:details }
frontpage_invoice_details:
    path:     /moje-konto/platnosci/faktura
    defaults: { _controller: AppPaymentBundle:Invoice:details }