services:
    payment.manager:
        class: App\PaymentBundle\Services\PaymentManager
        arguments: [@service_container]
    invoice.manager:
        class: App\PaymentBundle\Services\InvoiceManager
        arguments: [@service_container]
    sms.manager:
        class: App\PaymentBundle\Services\SmsPremiumManager
        arguments: [@service_container]
    card.manager:
        class: App\PaymentBundle\Services\Przelewy24Manager
        arguments: [@service_container]
    subscription_payment.manager:
        class: App\PaymentBundle\Services\SubscriptionManager
        arguments: [@service_container]
    payment.twig.function_extension:
        class: App\PaymentBundle\Twig\FunctionExtension
        arguments: []
        tags:
            - { name: twig.extension }
    payment.report_manager:
        class: App\PaymentBundle\Services\ReportManager
        arguments: [@templating, @payment.manager,@tfox.mpdfport]

    app.payment_voter:
        class: App\PaymentBundle\Security\PaymentVoter
        arguments: [@security.access.decision_manager]
        tags:
            - { name: security.voter }
    app.invoice_voter:
        class: App\PaymentBundle\Security\InvoiceVoter
        arguments: [@security.access.decision_manager]
        tags:
            - { name: security.voter }