App\PaymentBundle\Entity\Transaction:
    properties:
        publication:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        paymentMethod:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        value:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        smsCode:
            - NotBlank: {message: "Pole jest wymagane", groups: [sms]}
        agreeRegulations:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        agreeProcessingData:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        firstName:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        lastName:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        email:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
            - Email: {message: "Podany adres jest nieprawidłowy", groups: [card]}
        adrress:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        city:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        zipCode:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}
        country:
            - NotBlank: {message: "Pole jest wymagane", groups: [card]}