app_settings_edit_meta_tags:
    path:     /backoffice/editMetaTags
    defaults: { _controller: AppSettingsBundle:Settings:editMetaTags }
app_settings_edit_company_address:
    path:     /backoffice/editCompanyAddress
    defaults: { _controller: AppSettingsBundle:Settings:editCompanyAddress }
app_settings_edit_colors:
    path:     /backoffice/editColors
    defaults: { _controller: AppSettingsBundle:Settings:editColors }
app_settings_edit_my_image:
    path:     /backoffice/editMyImage
    defaults: { _controller: AppSettingsBundle:MyImage:edit }

app_settings_list_my_image:
    path:     /backoffice/listMyImage
    defaults: { _controller: AppSettingsBundle:MyImage:list }
app_settings_add_my_image:
    path:     /backoffice/addMyImage
    defaults: { _controller: AppSettingsBundle:MyImage:add }
app_settings_delete_my_image:
    path:     /backoffice/deleteMyImage
    defaults: { _controller: AppSettingsBundle:MyImage:delete }
app_settings_change_enabled_my_image:
    path:     /backoffice/changeEnabledMyImage
    defaults: { _controller: AppSettingsBundle:MyImage:changeEnabled }


backoffice_settings_link_list:
    pattern:   /backoffice/settings/links/list
    defaults:  { _controller: AppSettingsBundle:Link:list }

backoffice_settings_link_add:
    pattern:   /backoffice/settings/link/add
    defaults:  { _controller: AppSettingsBundle:Link:add }

backoffice_settings_link_delete:
    pattern:   /backoffice/settings/link/{id}/delete
    defaults:  { _controller: AppSettingsBundle:Link:delete }

backoffice_settings_link_edit:
    pattern:   /backoffice/settings/link/{id}/edit
    defaults:  { _controller: AppSettingsBundle:Link:edit }

backoffice_settings_link_change_order:
    pattern:   /backoffice/settings/link/{id}/order/{direction}
    defaults: { _controller: AppSettingsBundle:Link:changeOrdering }
