<?php

namespace App\NewsletterBundle\Entity;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
