app_office_www_homepage:
    path:     /
    host:     "www.{subdomain}.{domain}"
    defaults:
        _controller: AppOfficeBundle:Office:show
        domain: '%domain%'
    requirements:
        subdomain: "^((?!www).)*$"
        domain: '%domain%'

app_office_homepage:
    path:     /
    host:     "{subdomain}.{domain}"
    defaults:
        _controller: AppOfficeBundle:Office:show
        domain: '%domain%'
    requirements:
        subdomain: "^((?!www).)*$"
        domain: '%domain%'

app_front_page_homepage:
    path:     /
    defaults:
        _controller: AppFrontPageBundle:FrontPage:show

app_main_frontpage:
    path:     /
    host:     "{domain}"
    defaults:
        _controller: AppArchiveBundle:FrontPage:show
        domain: '%domain%'
    requirements:
        domain: '%domain%'

app_front_page_additional_services:
    path:     /dodatkowe-uslugi-wgn.html
    defaults: { _controller: AppFrontPageBundle:StaticPage:additionalServices }
sitemap:
    path:     /mapa-strony.html
    defaults: { _controller: AppFrontPageBundle:StaticPage:sitemap}
embed_search:
    path:     /umiesc-wyszukiwarke.html
    defaults: { _controller: AppFrontPageBundle:StaticPage:embedSearch}
subscription_offers:
    path:     /prenumerata-ofert.html
    defaults: { _controller: AppFrontPageBundle:StaticPage:subscriptionOffers}
app_import_articles:
    path:     /import_articles
    defaults: { _controller: AppFrontPageBundle:FrontPage:importArticles}


#### redirct z wgn.pl

redirect_pictures:
    path: /pictures/{params}.jpg
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: app_front_page_homepage
      permanent: true

redirect_image:
    path: /image/{params}.jpg
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: app_front_page_homepage
      permanent: true