app_back_office_homepage:
    path:     /backoffice/dashboard
    defaults:
        _controller: AppBackOfficeBundle:Dashboard:show
        domain: '%domain%'
    requirements:
        domain: '%domain%'
app_back_office:
    path:     /backoffice/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_back_office_homepage
        permanent: true
        domain: '%domain%'
    requirements:
        domain: '%domain%'