backoffice_subscription_list:
    path:     /backoffice/subscription/list
    defaults: { _controller: AppSubscriptionBundle:Subscription:list }
backoffice_subscription_add:
    path:     /backoffice/subscription/add
    defaults: { _controller: AppSubscriptionBundle:Subscription:add }
backoffice_subscription_delete:
    path:     /backoffice/subscription/delete
    defaults: { _controller: AppSubscriptionBundle:Subscription:delete }
frontpage_subscription_details:
    path:     /moje-konto/subscription/details
    defaults: { _controller: AppSubscriptionBundle:Subscription:details }