frontend_offer_add_step_1:
    path:     /dodaj-oferte.html
    defaults: { _controller: AppOfferBundle:Offer:selectType}
frontend_offer_add_step_2:
    path:     /dodaj-oferte-krok-3.html
    defaults: { _controller: AppOfferBundle:Offer:add}
frontend_offer_add_step_3:
    path:     /dodaj-oferte-podglad.html
    defaults: { _controller: AppOfferBundle:Offer:preview}
frontend_offer_edit:
    path:     /moje-konto/edytuj-oferte.html
    defaults: { _controller: AppOfferBundle:Offer:edit}
frontend_offer_delete:
    path:     /moje-konto/usun-oferte.html
    defaults: { _controller: AppOfferBundle:Offer:delete}
frontend_offer_promo:
    path:     /moje-konto/promuj-oferte.html
    defaults: { _controller: AppOfferBundle:Offer:promo}
frontend_offer_renew:
    path:     /moje-konto/wystaw-ponownie.html
    defaults: { _controller: AppOfferBundle:Offer:renew}
frontend_offer_activate:
    path:     /moje-konto/aktywuj-oferte.html
    defaults: { _controller: AppOfferBundle:Offer:activate}
frontend_offer_confirm:
    path:     /dodaj-oferte-potwierdzenie.html
    defaults: { _controller: AppOfferBundle:Offer:confirm}
frontend_offer_payment:
    path:     /dodaj-oferte-zaplac.html
    defaults: { _controller: AppOfferBundle:Offer:payment}
frontend_offer_payment_success:
    path:     /dodaj-oferte-platnosc-przyjeta.html
    defaults: { _controller: AppOfferBundle:Offer:paymentSuccess}
frontend_offer_list:
    path:     /oferty.html
    defaults: { _controller: AppOfferBundle:Offer:list}
frontend_offers_on_map:
    path:     /mapa.html
    defaults: { _controller: AppOfferBundle:Offer:showOnMap}
frontend_offers_details_on_map:
    path:     /mapa/szczegoly-ogloszenie.html
    defaults: { _controller: AppOfferBundle:Offer:detailsOnMap}
frontend_location_autocomplete:
    path:     /szukaj/autocomplete.html
    defaults: { _controller: AppOfferBundle:Search:locationAutocomplete}
frontend_region_autocomplete:
    path:     /szukaj/region/autocomplete.html
    defaults: { _controller: AppOfferBundle:Search:regionAutocomplete}
frontend_city_autocomplete:
    path:     /szukaj/miaso/autocomplete.html
    defaults: { _controller: AppOfferBundle:Search:cityAutocomplete}
frontend_street_autocomplete:
    path:     /szukaj/ulica/autocomplete.html
    defaults: { _controller: AppOfferBundle:Search:streetAutocomplete}
frontend_price_autocomplete:
    path:     /szukaj/cena/autocomplete.html
    defaults: { _controller: AppOfferBundle:Search:priceAutocomplete }

frontend_offer_show:
    path:     /oferta/{id},{offerName}.html
    host:     "{domain}"
    defaults:
        _controller: AppOfferBundle:Offer:show
        domain: '%domain%'
    requirements:
        domain: '%domain%'

frontend_offer_show_phone:
    path:     /oferta/{id}/phone.html
    defaults: { _controller: AppOfferBundle:Offer:showPhone}
frontend_offer_send_message:
    path:     /offer/sendMessage
    defaults: { _controller: AppOfferBundle:Offer:sendMessage}
frontend_offer_image_add:
    path:     /offer/addImage
    defaults: { _controller: AppOfferBundle:Image:add}
frontend_offer_image_add_to_tmp:
    path:     /offer/tmp/addImage
    defaults: { _controller: AppOfferBundle:Image:addToTmp}
frontend_offer_image_delete:
    path:     /offer/imageDelete
    defaults: { _controller: AppOfferBundle:Image:delete}

frontend_category_offer_description_image_add:
  path:     /categoryOffersDescription/addImage
  defaults: { _controller: AppOfferBundle:CategoryOfferDescriptionImage:add }
frontend_category_offer_description_images_sort:
  path:     /categoryOffersDescription/imagesSort
  defaults: { _controller: AppOfferBundle:CategoryOfferDescriptionImage:sort }
frontend_category_offer_description_image_delete:
  path:     /categoryOffersDescription/imageDelete
  defaults: { _controller: AppOfferBundle:CategoryOfferDescriptionImage:delete }

frontend_offer_images_sort:
    path:     /offer/imagesSort
    defaults: { _controller: AppOfferBundle:Image:sort}

frontend_offer_observed_add:
    path:     /obserwowane/dodaj.html
    defaults: { _controller: AppOfferBundle:Observed:add}

frontend_offer_observed_remove:
    path:     /obserwowane/usun.html
    defaults: { _controller: AppOfferBundle:Observed:remove}
frontend_offer_observed_multi_remove:
    path:     /obserwowane/usun-wybrane.html
    defaults: { _controller: AppOfferBundle:Observed:multiRemove}

frontend_offer_observed_list:
    path:     /obserwowane/pokaz.html
    defaults: { _controller: AppUserBundle:User:observed}

frontend_available_countries:
    path:     /availableCountries
    defaults: { _controller: AppOfferBundle:Search:availableCountries}
frontend_search_embed:
    path:     /embed
    defaults: { _controller: AppOfferBundle:Search:embed}
frontend_search_partner:
    path:     /szukaj/partner
    defaults: { _controller: AppOfferBundle:Search:partner}
frontend_search_advanced_form:
    path:     /advanced/form
    defaults: { _controller: AppOfferBundle:Search:getAdvancedForm}
frontend_search_get_types:
    path:     /getTypes
    defaults: { _controller: AppOfferBundle:Search:getTypes}
frontend_search_get_category_types:
    path:     /getCategoryTypes/{idCategory}
    defaults: { _controller: AppOfferBundle:Search:getCategoryTypes}
frontend_send_abuse_message:
    path:     /send-abuse-message.html
    defaults: { _controller: AppOfferBundle:Offer:sendAbuseMessage}
frontend_results_notification:
    path:     /save-results-notifications.html
    defaults: { _controller: AppOfferBundle:Offer:resultsNotification}
frontend_offer_looking_for:
    path:     /poszukuje-nieruchomosci.html
    defaults: { _controller: AppOfferBundle:Offer:lookingFor}


redirect_najem:
  path: /najem/{type}/
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: frontend_offer_search_url
    transaction: wynajem
    permanent: true

redirect_kupno:
  path: /kupno/{type}/
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: frontend_offer_search_url
    transaction: sprzedaz
    permanent: true

redirect_najem_witch_location:
  path: /najem/{type}/{locationKey}/
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: frontend_offer_search_url_with_location
    transaction: wynajem
    permanent: true

redirect_kupnom_witch_location:
  path: /kupno/{type}/{locationKey}/
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: frontend_offer_search_url_with_location
    transaction: sprzedaz
    permanent: true

frontend_offer_list_office:
    path:     /oferty/wszystkie/
    defaults: { _controller: AppOfferBundle:Offer:listByUrl}

frontend_offer_list_agent:
    path:     /agent-{user}/oferty/wszystkie/
    defaults: { _controller: AppOfferBundle:Offer:listByUrl}

frontend_offer_search_url_agent_with_location:
    path:     /agent-{user}/{transaction}/{type}/{locationKey}/
    defaults: { _controller: AppOfferBundle:Offer:listByUrl}
    requirements:
        transaction: sprzedaz|kupno|wynajem|najem
        type:  mieszkanie|dom|dzialka|lokal|obiekt-komercyjny|garaz|nieruchomosc-komercyjna|komercyjne

frontend_offer_search_url_agent:
    path:     /agent-{user}/{transaction}/{type}/
    defaults: { _controller: AppOfferBundle:Offer:listByUrl}
    requirements:
        transaction: sprzedaz|kupno|wynajem|najem
        type:  mieszkanie|dom|dzialka|lokal|obiekt-komercyjny|garaz|nieruchomosc-komercyjna|komercyjne

frontend_offer_search_url_with_location:
    path:     /{transaction}/{type}/{locationKey}/
    defaults: { _controller: AppOfferBundle:Offer:listByUrl}
    requirements:
        transaction: sprzedaz|kupno|wynajem|najem
        type:  mieszkanie|dom|dzialka|lokal|obiekt-komercyjny|garaz|nieruchomosc-komercyjna|komercyjne

frontend_offer_search_url:
    path:     /{transaction}/{type}/
    defaults: { _controller: AppOfferBundle:Offer:listByUrl}
    requirements:
        transaction: sprzedaz|kupno|wynajem|najem
        type:  mieszkanie|dom|dzialka|lokal|obiekt-komercyjny|garaz|nieruchomosc-komercyjna|komercyjne

frontend_offer_search_subdomain:
    path:     /
    host:     "{subdomain}.{domain}"
    defaults:
        _controller: AppOfferBundle:Offer:listBySubdomain
        domain: '%domain%'
    requirements:
        subdomain: "^(([[:alnum:]]*-[[:alnum:]]*-[[:alnum:]-]*)*)$"
        domain: '%domain%'

frontend_offer_archive_subdomain:
    path:     /oferta/{id},{offerName}.html
    host:     "{subdomain}.{domain}"
    defaults:
        _controller: AppOfferBundle:Offer:show
        domain: '%domain%'
        subdomain: "archiwum"
    requirements:
        domain: '%domain%'
        subdomain: "archiwum"

frontend_offer_office_search_subdomain:
    path:     /oferta/{id},{offerName}.html
    host:     "{subdomain}.{domain}"
    defaults:
        _controller: AppOfferBundle:Offer:show
        domain: '%domain%'
    requirements:
        subdomain: "^(([[:alnum:]]*)*)$"
        domain: '%domain%'


frontend_offer_subdomain:
    path:     /oferta/{id},{offerName}.html
    host:     "{subdomain}.{domain}"
    defaults:
        _controller: AppOfferBundle:Offer:show
        domain: '%domain%'
    requirements:
        subdomain: "^(([[:alnum:]]*-[[:alnum:]]*-[[:alnum:]-]*)*)$"
        domain: '%domain%'

frontend_offers_to_komercja:
    path:     /of2json.php
    defaults: { _controller: AppOfferBundle:Offer:offersToKomercja}

backoffice_offer_clients:
    path:     /backoffice/offers/clients
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:list}
backoffice_offer_list:
    path:     /backoffice/offers/list
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:list}
backoffice_offer_modal_list:
    path:     /backoffice/offers/modalList
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:modalList}
backoffice_offer_add:
    path:     /backoffice/offers/add
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:add}
backoffice_offer_edit:
    path:     /backoffice/offers/edit
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:edit}
backoffice_offer_delete:
    path:     /backoffice/offers/delete
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:delete}
backoffice_offer_change_publish:
    path:     /backoffice/offers/changePublish
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:changePublish}
backoffice_offer_change_options:
    path:     /backoffice/offers/changeOptions
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:changeOptions}
backoffice_offer_preview:
    path:     /backoffice/offers/preview
    defaults: { _controller: AppOfferBundle:BackOfficeOffer:preview}

backoffice_offers_category_description_add:
    path:     /backoffice/offers/categoryDescription/add
    defaults: { _controller: AppOfferBundle:CategoryOfferDescription:add }

backoffice_offers_category_description_edit:
    path:     /backoffice/offers/categoryDescription/edit
    defaults: { _controller: AppOfferBundle:CategoryOfferDescription:edit }

backoffice_offers_category_description_list:
    path:     /backoffice/offers/categoryDescriptions
    defaults: { _controller: AppOfferBundle:CategoryOfferDescription:list }

backoffice_offers_category_description_delete:
    path:     /backoffice/offers/categoryDescription/delete
    defaults: { _controller: AppOfferBundle:CategoryOfferDescription:delete }


backoffice_offer_link_list:
  pattern:   /backoffice/offer/{idOffer}/links/list
  defaults:  { _controller: AppOfferBundle:Link:list }

backoffice_offer_link_add:
  pattern:   /backoffice/offer/{idOffer}/link/add
  defaults:  { _controller: AppOfferBundle:Link:add }

backoffice_offer_link_delete:
  pattern:   /backoffice/offer/link/{id}/delete
  defaults:  { _controller: AppOfferBundle:Link:delete }

backoffice_offer_link_edit:
  pattern:   /backoffice/offer/link/{id}/edit
  defaults:  { _controller: AppOfferBundle:Link:edit }

backoffice_offer_link_change_order:
  pattern:   /backoffice/offer/link/{id}/order/{direction}
  defaults: { _controller: AppOfferBundle:Link:changeOrdering }


######## redirect z wgn.pl
redirect_nieruchomosc:
    path: /nieruchomosc/{signature}/{name}.html
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: app_front_page_homepage
      permanent: true

redirect_nieruchomosc2:
    path: /i4/o,{signature},{a},{b},{name}.html
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: app_front_page_homepage
      permanent: true

redirect_nieruchomosc3:
    path: /i/o,{signature},{a},{lang},{name}.html
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: app_front_page_homepage
      permanent: true
redirect_nieruchomosc4:
    path: /nieruchomosc/{signature}/{name}
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      permanent: true

redirect_nieruchomosc5:
    path: /i/b,l,{name},{c},{lang},list.html
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      permanent: true

redirect_nieruchomosc6:
    path: /nieruchomosc/{signature}
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      permanent: true
redirect_mieszkania:
    path: /mieszkania
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 1
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_domy:
    path: /domy
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 2
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_apartamenty:
    path: /apartamenty
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 1
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_wille_rezydencje:
    path: /wille_rezydencje
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 2
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_wille_rezydencje2:
    path: /dwory_posiadlosci
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 2
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_palace_zamki:
    path: /palace_zamki
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 2
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_grunty:
    path: /grunty
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 3
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_gospodarstwa_rolne:
    path: /gospodarstwa_rolne
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 3
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_garaze:
    path: /garaze
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 6
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_biurowce:
    path: /biurowce
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_kamienice:
    path: /kamienice
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_budynki_wielorodzinne2:
    path: /budynki_wielorodzinne
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_budynki_handlowo_uslugowe:
    path: /budynki_handlowo_uslugowe
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true


redirect_hotele:
    path: /hotele
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true


redirect_obiekty_rekreacyjno_gastronomiczne:
    path: /obiekty_rekreacyjno_gastronomiczne
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true


redirect_budynki_wielorodzinne:
    path: /obiekty_magazynowo_przemyslowe
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_lokale:
    path: /lokale
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_inne:
    path: /inne
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_apartamenty2:
    path: /apartamenty/{p1}/{p2}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: frontend_offer_list
        search[category]: 1
        search[transactionType]: 1
        search[country]: 1
        permanent: true

redirect_domy2:
    path: /domy/{p1}/{p2}
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 2
      search[transactionType]: 1
      search[country]: 1
      permanent: true

redirect_grunty2:
    path: /grunty/{p1}/{p2}
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 3
      search[transactionType]: 1
      search[country]: 1
      permanent: true
redirect_lokale2:
    path: /lokale/{p1}/{p2}
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      search[category]: 5
      search[transactionType]: 1
      search[country]: 1
      permanent: true
redirect_i_php:
    path: /i.php/{p}
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: frontend_offer_list
      permanent: true
get_offer_images_ajax:
  path:     /offer/{id}/images
  defaults: { _controller: AppOfferBundle:Image:getImagesOffer }
  options:
    expose: true

