App\OfferBundle\Entity\Offer:
    properties:
        country:
            - NotBlank: {message: "Pole jest wymagane", groups: [add]}
        region:
            - NotBlank: {message: "Pole jest wymagane", groups: [add]}
        city:
            - NotBlank: {message: "Pole jest wymagane", groups: [add]}
        name:
            - NotBlank: {message: "Pole jest wymagane", groups: [add]}
        description:
            - NotBlank: {message: "Pole jest wymagane", groups: [add]}
        email:
            - NotBlank: {message: "Pole jest wymagane", groups: [add]}
            - Email: {message: "Podany adres e-mail jest nieprawidłowy", groups: [add]}

App\OfferBundle\Model\Contact:
    properties:
        message:
            - NotBlank: {message: "Pole jest wymagane"}
        email:
            - NotBlank: {message: "Pole jest wymagane"}
            - Email: {message: "Podany adres e-mail jest nieprawidłowy"}
        offer:
            - NotBlank: {message: "Pole jest wymagane"}
        agree:
            - NotBlank: {message: "Pole jest wymagane"}
App\OfferBundle\Model\LookingFor:
    properties:
        email:
            - NotBlank: {message: "Pole jest wymagane"}
            - Email: {message: "Podany adres e-mail jest nieprawidłowy"}
        transaction:
            - NotBlank: {message: "Pole jest wymagane"}
        transaction:
            - NotBlank: {message: "Pole jest wymagane"}
        country:
            - NotBlank: {message: "Pole jest wymagane"}
        province:
            - NotBlank: {message: "Pole jest wymagane"}
        city:
            - NotBlank: {message: "Pole jest wymagane"}
        squereFrom:
            - NotBlank: {message: "Pole jest wymagane"}
        squereTo:
            - NotBlank: {message: "Pole jest wymagane"}
        roomsFrom:
            - NotBlank: {message: "Pole jest wymagane"}
        roomsTo:
            - NotBlank: {message: "Pole jest wymagane"}
        floorFrom:
            - NotBlank: {message: "Pole jest wymagane"}
        floorTo:
            - NotBlank: {message: "Pole jest wymagane"}
        priceFrom:
            - NotBlank: {message: "Pole jest wymagane"}
        priceTo:
            - NotBlank: {message: "Pole jest wymagane"}
        currency:
            - NotBlank: {message: "Pole jest wymagane"}
        name:
            - NotBlank: {message: "Pole jest wymagane"}

App\OfferBundle\Entity\Link:
    properties:
        name:
            - NotBlank: ~
        url:
            - NotBlank: ~
        color:
            - NotBlank: ~
